<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
   <!-- <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
    Core GraphQL Runtime Engine for ASP.NET Core -->
    <PackageReference Include="HotChocolate.AspNetCore" Version="13.9.0" />
    
    <!-- GraphQL Data Projection and Performance Mapping Layer -->
    <PackageReference Include="HotChocolate.Data" Version="13.9.0" />
    <!-- Ultra-fast Micro-ORM for Senior Data Access -->
    <PackageReference Include="Dapper" Version="2.1.35" />
    <!-- Microsoft SQL Server Native Data Client Driver -->
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Legacy.Bridge.VbNet\Legacy.Bridge.VbNet.vbproj" />
  </ItemGroup>

</Project>
